"""Historical holdout demo: display artifacts generated by the notebook."""
import hashlib
import json
from pathlib import Path

import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parents[1]
st.set_page_config(page_title="Predictive Lead Ranking", layout="wide")
st.title("Predictive Lead Ranking")
st.write("Historical bank-marketing data · a fixed top-100 contact-capacity scenario")

try:
    evaluation = json.loads((ROOT / "data/model_evaluation.json").read_text())
    csv_path = ROOT / "data/top_leads.csv"
    leads = pd.read_csv(csv_path)
    holdout = evaluation["holdout"]
    ranking = evaluation["ranking"]
    if hashlib.sha256(csv_path.read_bytes()).hexdigest() != evaluation["top_leads_sha256"]:
        raise ValueError("The lead export and evaluation file do not belong to the same run.")
    if len(leads) != ranking["top_k"] or int(leads["actual_outcome"].sum()) != ranking["positives_captured_at_k"]:
        raise ValueError("The lead export does not match the evaluation counts.")
except (OSError, ValueError, KeyError) as exc:
    st.error(f"Cannot load consistent analysis artifacts: {exc}. Run the notebook to regenerate them.")
    st.stop()

st.caption(
    f"Selected model: {evaluation['selected_model']} · "
    f"Training-only {evaluation['selection']['folds']}-fold cross-validation selected by average precision."
)
st.info(
    "This is a retrospective holdout demonstration. Scores order historical records; they are not "
    "calibrated individual conversion probabilities or evidence of extra conversions caused by calling."
)
cols = st.columns(4)
cols[0].metric("Holdout records", f"{holdout['size']:,}")
cols[1].metric("Holdout positive prevalence", f"{holdout['positive_prevalence']:.2%}")
cols[2].metric("Average precision", f"{holdout['average_precision']:.3f}")
cols[3].metric("ROC-AUC", f"{holdout['roc_auc']:.3f}")

st.subheader(f"Capacity decision: prioritize {ranking['top_k']} records")
cols = st.columns(4)
cols[0].metric("Historical positives captured", f"{ranking['positives_captured_at_k']} / {ranking['top_k']}")
cols[1].metric("Precision@100", f"{ranking['precision_at_k']:.1%}")
cols[2].metric("Capture@100", f"{ranking['capture_at_k']:.2%}")
cols[3].metric("Lift@100", f"{ranking['lift_at_k']:.2f}×")
st.write(
    f"Select the highest model scores within a capacity of {ranking['top_k']} records "
    f"({ranking['capacity_fraction']:.2%} of the holdout). This selection contains "
    f"{ranking['positives_captured_at_k']} historical positives; random selection at the same "
    f"capacity would contain {ranking['random_expected_positives_at_k']:.1f} on average. "
    "Lift is precision divided by prevalence in this holdout, not causal uplift."
)

st.subheader("Ranked historical records")
st.caption(
    "Top 100 is a capacity label. Source row ID is a zero-based dataset row, not a verified customer ID. "
    "Actual outcome is known only afterward and is shown solely for evaluation. Ties use ascending source row ID."
)
st.dataframe(
    leads,
    hide_index=True,
    width="stretch",
    height=390,
    column_config={
        "source_row_id": st.column_config.NumberColumn("Source row ID", format="%d"),
        "model_score": st.column_config.NumberColumn("Model score (uncalibrated)", format="%.4f"),
        "priority": "Capacity selection",
        "actual_outcome": st.column_config.NumberColumn("Actual outcome (known afterward)", format="%d"),
    },
)
st.caption(
    "Pre-contact features: client attributes and prior-campaign history. Current-contact fields and pdays "
    "are excluded. Client snapshot timing is assumed, not independently verified. "
    "Random historical splitting does not establish future performance or unique-customer separation."
)
